<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>35fb7f5c-1f97-4eb3-81fe-6743ef1dd18f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusAI.Application\NexusAI.Application.csproj" />
    <ProjectReference Include="..\NexusAI.Domain\NexusAI.Domain.csproj" />
    <ProjectReference Include="..\NexusAI.Infrastructure\NexusAI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
