<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusAI.Core\NexusAI.Core.csproj" />
    <ProjectReference Include="..\NexusAI.Foundation\NexusAI.Foundation.csproj" />
	  <ProjectReference Include="..\NexusAI.Domain\NexusAI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Conversations\" />
    <Folder Include="Knowledge\" />
    <Folder Include="Agents\" />
  </ItemGroup>

</Project>
