<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>NexusAI.Domain</AssemblyName>
		<RootNamespace>NexusAI.Domain</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NexusAI.Core\NexusAI.Core.csproj" />
		<ProjectReference Include="..\NexusAI.Foundation\NexusAI.Foundation.csproj" />
	</ItemGroup>

</Project>