<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Nexus.Platform.Providers.Anthropic</RootNamespace>
    <AssemblyName>Nexus.Platform.Providers.Anthropic</AssemblyName>
    <IsPackable>true</IsPackable>
    <PackageId>Nexus.Platform.Providers.Anthropic</PackageId>
    <Authors>PRT</Authors>
    <Description>Nexus V2 - Nexus.Platform.Providers.Anthropic</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Platform.Contracts\Nexus.Platform.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
  </ItemGroup>

</Project>

